package com.byz.factory.iot.repository;

import com.byz.factory.iot.*;
import com.byz.factory.iot.model.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ContextConfiguration;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@ContextConfiguration(classes = IotTestConfig.class)
@DisplayName("IoT Repository 集成测试")
class IotRepositoryTest {

    @Autowired
    private DeviceConnectionRepository connRepo;

    @Autowired
    private TagValueRepository tagRepo;

    @Autowired
    private CommandRepository cmdRepo;

    @Autowired
    private AlarmEventRepository alarmRepo;

    @BeforeEach
    void setUp() {
        alarmRepo.deleteAll();
        cmdRepo.deleteAll();
        tagRepo.deleteAll();
        connRepo.deleteAll();
    }

    // ==================== DeviceConnectionRepository ====================

    @Test
    @DisplayName("保存并查询设备连接 — findByCode")
    void deviceConnection_saveAndFindByCode() {
        // Given
        DeviceConnection conn = new DeviceConnection("EQ-001", "OPC_UA", "opc.tcp://192.168.1.100:4840");

        // When
        connRepo.save(conn);
        DeviceConnection found = connRepo.findByCode("EQ-001");

        // Then
        assertNotNull(found);
        assertEquals("OPC_UA", found.getProtocol());
        assertEquals(1000, found.getPollIntervalMs());
    }

    @Test
    @DisplayName("按协议筛选连接 — findByProtocol")
    void deviceConnection_findByProtocol() {
        // Given
        connRepo.save(new DeviceConnection("EQ-001", "OPC_UA", "opc.tcp://192.168.1.100:4840"));
        connRepo.save(new DeviceConnection("EQ-002", "MODBUS_TCP", "192.168.1.101:502"));
        connRepo.save(new DeviceConnection("EQ-003", "OPC_UA", "opc.tcp://192.168.1.102:4840"));

        // When
        List<DeviceConnection> opcUa = connRepo.findByProtocol("OPC_UA");

        // Then
        assertEquals(2, opcUa.size());
    }

    @Test
    @DisplayName("设备连接 ID 自增")
    void deviceConnection_idAutoGenerated() {
        // Given
        DeviceConnection conn = new DeviceConnection("EQ-004", "MQTT", "tcp://broker:1883");

        // When
        DeviceConnection saved = connRepo.save(conn);

        // Then
        assertNotNull(saved.getId());
    }

    // ==================== TagValueRepository ====================

    @Test
    @DisplayName("保存并查询标签值 — findByEquipmentCodeAndTagName")
    void tagValue_saveAndFindByEquipmentAndTag() {
        // Given
        TagValue tv = TagValue.of("EQ-001", "TEMP_001", new BigDecimal("82.5"));

        // When
        tagRepo.save(tv);
        List<TagValue> results = tagRepo.findByEquipmentCodeAndTagName("EQ-001", "TEMP_001");

        // Then
        assertEquals(1, results.size());
        assertEquals(new BigDecimal("82.5"), results.get(0).getScaledValue());
        assertEquals(ITagValue.TagQuality.GOOD, results.get(0).getQuality());
    }

    @Test
    @DisplayName("按设备编码查找所有标签值")
    void tagValue_findByEquipmentCode() {
        // Given
        tagRepo.save(TagValue.of("EQ-001", "TEMP", new BigDecimal("120.0")));
        tagRepo.save(TagValue.of("EQ-001", "PRESS", new BigDecimal("5.0")));
        tagRepo.save(TagValue.of("EQ-002", "SPEED", new BigDecimal("3000")));

        // When
        List<TagValue> eq001Tags = tagRepo.findByEquipmentCode("EQ-001");

        // Then
        assertEquals(2, eq001Tags.size());
    }

    @Test
    @DisplayName("按批次 ID 查找标签值")
    void tagValue_findByBatchId() {
        // Given
        TagValue tv1 = TagValue.of("EQ-001", "TEMP", BigDecimal.TEN);
        tv1.setBatchId("BATCH-001");
        TagValue tv2 = TagValue.of("EQ-001", "PRESS", BigDecimal.ONE);
        tv2.setBatchId("BATCH-001");
        TagValue tv3 = TagValue.of("EQ-002", "TEMP", BigDecimal.TEN);
        tv3.setBatchId("BATCH-002");

        tagRepo.saveAll(List.of(tv1, tv2, tv3));

        // When
        List<TagValue> batch1 = tagRepo.findByBatchId("BATCH-001");

        // Then
        assertEquals(2, batch1.size());
    }

    // ==================== CommandRepository ====================

    @Test
    @DisplayName("保存并查询指令 — findByCode")
    void command_saveAndFindByCode() {
        // Given
        Command cmd = new Command("CMD-001", "EQ-001",
                ICommand.CommandType.SET_PARAM, Map.of("TEMP", 120.0));

        // When
        cmdRepo.save(cmd);
        Command found = cmdRepo.findByCode("CMD-001");

        // Then
        assertNotNull(found);
        assertEquals(CommandStatus.QUEUED, found.getStatus());
        assertEquals("EQ-001", found.getEquipmentCode());
    }

    @Test
    @DisplayName("按设备编码查找指令")
    void command_findByEquipmentCode() {
        // Given
        Command cmd1 = new Command("CMD-002", "EQ-001",
                ICommand.CommandType.START, Map.of());
        Command cmd2 = new Command("CMD-003", "EQ-002",
                ICommand.CommandType.STOP, Map.of());
        cmdRepo.saveAll(List.of(cmd1, cmd2));

        // When
        List<Command> eq001Cmds = cmdRepo.findByEquipmentCode("EQ-001");

        // Then
        assertEquals(1, eq001Cmds.size());
    }

    @Test
    @DisplayName("按状态查找指令 — findByStatus")
    void command_findByStatus() {
        // Given
        Command cmd1 = new Command("CMD-004", "EQ-001", ICommand.CommandType.START, Map.of());
        cmd1.markSent();
        Command cmd2 = new Command("CMD-005", "EQ-002", ICommand.CommandType.STOP, Map.of());
        cmdRepo.saveAll(List.of(cmd1, cmd2));

        // When
        List<Command> queued = cmdRepo.findByStatus(CommandStatus.QUEUED);
        List<Command> sent = cmdRepo.findByStatus(CommandStatus.SENT);

        // Then
        assertEquals(1, queued.size());
        assertEquals(1, sent.size());
    }

    @Test
    @DisplayName("JSON 参数序列化 — Map 存取")
    void command_jsonParameters_roundTrip() {
        // Given
        Map<String, Object> params = Map.of("SPEED", 5000, "TEMP", 220.5, "ENABLED", true);
        Command cmd = new Command("CMD-006", "EQ-003", ICommand.CommandType.SET_PARAM, params);

        // When
        cmdRepo.save(cmd);
        Command found = cmdRepo.findByCode("CMD-006");

        // Then: Map 参数应正确恢复
        assertNotNull(found.getParameters());
        assertEquals(5000, found.getParameters().get("SPEED"));
        assertEquals(220.5, found.getParameters().get("TEMP"));
        assertEquals(true, found.getParameters().get("ENABLED"));
    }

    // ==================== AlarmEventRepository ====================

    @Test
    @DisplayName("保存并查询报警 — findByCode")
    void alarmEvent_saveAndFindByCode() {
        // Given
        AlarmEvent alarm = new AlarmEvent("TEMP_HIGH", "EQ-001",
                IAlarmEvent.AlarmSeverity.CRITICAL,
                new BigDecimal("135.0"), new BigDecimal("130.0"));

        // When
        alarmRepo.save(alarm);
        AlarmEvent found = alarmRepo.findByCode("TEMP_HIGH");

        // Then
        assertNotNull(found);
        assertEquals(IAlarmEvent.AlarmSeverity.CRITICAL, found.getSeverity());
        assertEquals(new BigDecimal("135.0"), found.getTriggerValue());
    }

    @Test
    @DisplayName("查找未恢复的报警 — findActiveAlarms")
    void alarmEvent_findActiveAlarms() {
        // Given
        AlarmEvent alarm1 = new AlarmEvent("ALM-001", "EQ-001",
                IAlarmEvent.AlarmSeverity.WARNING,
                new BigDecimal("85.0"), new BigDecimal("80.0"));
        AlarmEvent alarm2 = new AlarmEvent("ALM-002", "EQ-002",
                IAlarmEvent.AlarmSeverity.CRITICAL,
                new BigDecimal("200.0"), new BigDecimal("180.0"));
        alarm2.resolve(); // 已恢复
        alarmRepo.saveAll(List.of(alarm1, alarm2));

        // When
        List<AlarmEvent> active = alarmRepo.findActiveAlarms();

        // Then
        assertEquals(1, active.size());
        assertEquals("ALM-001", active.get(0).getAlarmCode());
    }

    @Test
    @DisplayName("按设备查找未恢复的报警 — findActiveAlarmsByEquipment")
    void alarmEvent_findActiveAlarmsByEquipment() {
        // Given
        AlarmEvent alarm1 = new AlarmEvent("ALM-003", "EQ-001",
                IAlarmEvent.AlarmSeverity.WARNING,
                new BigDecimal("85.0"), new BigDecimal("80.0"));
        AlarmEvent alarm2 = new AlarmEvent("ALM-004", "EQ-002",
                IAlarmEvent.AlarmSeverity.WARNING,
                new BigDecimal("90.0"), new BigDecimal("85.0"));
        alarmRepo.saveAll(List.of(alarm1, alarm2));

        // When
        List<AlarmEvent> active = alarmRepo.findActiveAlarmsByEquipment("EQ-001");

        // Then
        assertEquals(1, active.size());
        assertEquals("ALM-003", active.get(0).getAlarmCode());
    }

    @Test
    @DisplayName("报警确认 — acknowledge 更新字段")
    void alarmEvent_acknowledge_updatesFields() {
        // Given
        AlarmEvent alarm = new AlarmEvent("ALM-005", "EQ-003",
                IAlarmEvent.AlarmSeverity.CRITICAL,
                new BigDecimal("150.0"), new BigDecimal("140.0"));
        alarmRepo.save(alarm);

        // When
        AlarmEvent found = alarmRepo.findByCode("ALM-005");
        found.acknowledge("操作员张三");
        alarmRepo.save(found);

        // Then
        AlarmEvent updated = alarmRepo.findByCode("ALM-005");
        assertEquals("操作员张三", updated.getAcknowledgedBy());
        assertNotNull(updated.getAcknowledgedAt());
        assertTrue(updated.isAcknowledged());
    }

    @Test
    @DisplayName("报警恢复 — resolve 设置 resolvedAt")
    void alarmEvent_resolve_setsResolvedTime() {
        // Given
        AlarmEvent alarm = new AlarmEvent("ALM-006", "EQ-004",
                IAlarmEvent.AlarmSeverity.WARNING,
                new BigDecimal("85.0"), new BigDecimal("80.0"));
        alarmRepo.save(alarm);

        // When
        AlarmEvent found = alarmRepo.findByCode("ALM-006");
        found.resolve();
        alarmRepo.save(found);

        // Then
        AlarmEvent updated = alarmRepo.findByCode("ALM-006");
        assertNotNull(updated.getResolvedAt());
        assertTrue(updated.isResolved());
    }

    @Test
    @DisplayName("JSON 联动动作 — List 存取")
    void alarmEvent_jsonActions_roundTrip() {
        // Given
        AlarmEvent alarm = new AlarmEvent("ALM-007", "EQ-005",
                IAlarmEvent.AlarmSeverity.EMERGENCY,
                new BigDecimal("200.0"), new BigDecimal("180.0"));
        alarm.addAction("STOP_MACHINE");
        alarm.addAction("NOTIFY_SUPERVISOR");

        // When
        alarmRepo.save(alarm);
        AlarmEvent found = alarmRepo.findByCode("ALM-007");

        // Then
        assertNotNull(found.getActions());
        assertTrue(found.getActions().contains("STOP_MACHINE"));
        assertTrue(found.getActions().contains("NOTIFY_SUPERVISOR"));
    }

    @Test
    @DisplayName("时间戳字段正确保存 — createdAt 自动填充")
    void entity_createdAt_shouldBeAutoFilled() {
        // Given
        DeviceConnection conn = new DeviceConnection("EQ-010", "HTTP", "http://localhost:8080");

        // When
        DeviceConnection saved = connRepo.save(conn);

        // Then
        assertNotNull(saved.getCreatedAt());
        assertNotNull(saved.getUpdatedAt());
        assertNotNull(saved.getId());
    }

}
